### ISSUE TITLE
开发进度计划

### ISSUE THREAD

**Issue by tigerzhang** [neverchanje/yaraft#2]
这个项目很有趣，做了我们曾经想做的事情。
想询问下你们的开发计划，看我们有没有机会在什么时间点参与。

**Comment by neverchanje** [comment]
不好意思之前没有看到这条 issue。
我的项目总共分为两部分，一部分是状态机，就是 yaraft；一部分是日志存储，就是 consensus-yaraft。
当下的开发计划是将 snapshotting 和 membership reconfiguration 加入 yaraft，做好充分测试后我会引入 consensus-yaraft。
项目的文档在 https://docs.google.com/document/d/17vLR0jWndw3S_7z3NRSTLyb4xI_Gq4LlZGXtg5j6sfs/edit?usp=sharing 。有兴趣可以阅读一下。
比较重头的部分在 consensus-yaraft，这个项目暂时还未上线，需要非常多的监控和性能测试工作。
非常希望你们能够参与进来。

**Comment by tigerzhang** [comment]
多谢回复。
我们目前的系统是基于 ongardie 的 logcabin 做的，基本上所有的特性都已经实现了，但是跟 etcd 比起来，测试用例和在生产环境的使用案例少。
如果有一个 etcd raft 实现的 c++ 版本，会是一个很好的解决方向。毕竟我们也不准备在这么核心的模块里面采用 go。

**Comment by neverchanje** [comment]
事实上 etcd/raft 提供的只是状态机的实现，当然它是十分核心的。然而在它之上实现 wal 和 rpc 同样要占比较大一块工作量。所以 logcabin 不应该和 etcd/raft 做对比。
相比 logcabin，consensus-yaraft 所提供的特性包括：

- 基于事件的状态机模型。这是 etcd/raft 的特性。全异步，单线程状态机，避免加锁。
- 单台机器上多 raft 节点之间可以共享资源，这是针对分布式数据库系统优化的。

这个项目现在还在初期，如果你们团队有兴趣了解代码，我可以给你们提供帮助。

**Comment by xiang90** [comment]
etcd/raft 协议目前有go/rust版本 java有人在做。c++目前这个库是进展比较快的。

我们希望所有不同版本的etcd/raft协议 尽量能保持sync。etcd/raft在开发的时候，就尽量少用go的特性，可以容易的port到其它语言。

我们后期应该会把raft做成一个独立的项目，然后把各个语言的port都拉进来。

**Comment by neverchanje** [comment]
可以，我也在持续关注 etcd/raft 的一些更新。
