### ISSUE TITLE
handleSnapshotResp 存疑

### ISSUE THREAD

**Issue by w41ter** [neverchanje/yaraft#4]
https://github.com/neverchanje/yaraft/blob/1d831c06574879de2c97bb3c3a84a4e899f55005/src/raft.h#L913

这里说快照安装成功，pause 并等一个 appendResp，但是在：

https://github.com/neverchanje/yaraft/blob/1d831c06574879de2c97bb3c3a84a4e899f55005/src/raft.h#L571

这里判断了如果处于 pause 是不会发送 appendRequest 的。

希望能得到解答。

**Comment by w41ter** [comment]
emmm，找到答案了，实际上 sendHeartbeat 不会判断是否处于 paused 状态，

https://github.com/neverchanje/yaraft/blob/1d831c06574879de2c97bb3c3a84a4e899f55005/src/raft.h#L556

https://github.com/neverchanje/yaraft/blob/1d831c06574879de2c97bb3c3a84a4e899f55005/src/raft.h#L633-L649

通识在 handleHeartbeatResp 中会调用 resume()，

https://github.com/neverchanje/yaraft/blob/1d831c06574879de2c97bb3c3a84a4e899f55005/src/raft.h#L654-L658

所以。。。

**Comment by neverchanje** [comment]
恩, 这块是比较复杂.
现在 snapshotting 这块我一直没有再跟进, 你有兴趣的话可以帮忙在 consensus-yaraft 里加上 snapshotting.
