### ISSUE TITLE
pre-vote response will be ignore

### ISSUE THREAD

**Issue by w41ter** [neverchanje/yaraft#5]
https://github.com/neverchanje/yaraft/blob/1d831c06574879de2c97bb3c3a84a4e899f55005/src/raft.h#L505-L522

to explain briefly, suppose there are five nodes: 
A, B, C, D, E. 
A win the first campgin and become leader, current term is:
 A, B, C, D, E: -> 1. 
Now A, B is partitioned away, C,D,E start the next campgin and C win, current term is: 
A, B: -> 1.
C, D, E: -> 2.
After committed some entries, C,D is partitioned away, and A, B rejoin clusters.

when E send pre-vote request to A, B, A, B send pre-vote response with local term(1), E will proceed to ignore the message.
when A, B send pre-vote request to E, E will ignore this messages too.

https://github.com/neverchanje/yaraft/blob/1d831c06574879de2c97bb3c3a84a4e899f55005/src/raft.h#L91-L105

so no one will win the campgin.

I found a solution in TIKV's Raft implementation：

https://github.com/pingcap/raft-rs/blob/99fe6050c708f936012305f6006795344680d93a/src/raft.rs#L1044-L1060

**Comment by neverchanje** [comment]
sorry for late response... 最近重写了一遍这个项目，基本已经和 etcd/raft 保持一致，为了保证代码一致，所有 feature 和所有的 codes 所有的 tests 都抄了过来。相信应该没你说的问题了。
