### ISSUE TITLE
etcd-raft node

### ISSUE THREAD

**Issue by wgtdkp** [neverchanje/yaraft#6]
我粗略看了一下，请问etcd-raft的node还没有实现吗？没有找到。

**Comment by neverchanje** [comment]
对，只有 raw_node 的实现，c++ 比较难实现 node

**Comment by wgtdkp** [comment]
node里面的channel就用queue做啊，为什么难？

**Comment by neverchanje** [comment]
你可以衡量工程量和收益，有兴趣可以再给 yaraft 提 PR, 欢迎你有想法可以在这里尝试

**Comment by wgtdkp** [comment]
可能是我看的不仔细，你的`Raft`和`RawNode`都是无锁的，怎么保证安全的？

**Comment by neverchanje** [comment]
单线程运行一个 raw node 状态机，保证无 contention，这样就是无锁的

**Comment by wgtdkp** [comment]
IO同步的？

**Comment by neverchanje** [comment]
不管同步异步都会把 raw node 固定在一个线程上

**Comment by wgtdkp** [comment]
嗯，你的“把一个异步IO事件投递到指定worker线程”的那部分代码是哪里呢？

**Comment by neverchanje** [comment]
所以这个项目只做了状态机, etcd/raft 也只做了状态机

**Comment by wgtdkp** [comment]
👌
